### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by Ructar** [SSPU1W/dbjailer#2]
Hey man, I know that you dont want this code to be used on live servers. Anyway I can get your permission to have it on mine? I'm looking for something like this, and you are one of the only esx mods that work. I don't want to use it without any permission.

**Comment by SSPU1W** [comment]
As I said, this is not to be used on live servers, no exceptions. If it is seen being used by me or anyone in the rp community who I know legal action will be taken against said servers.

**Comment by SSPU1W** [comment]
You may use this script now.
